### ISSUE TITLE
"No connection adapters were found for" - getting same error in both docker method, and with installed python

### ISSUE THREAD

**Issue by CarlInglis** [pawelrychlik/jira-dependency-graph#29]
```
$ python jira-dependency-graph.py --user=[username] --password=[password] -jira=https://[FQDN] --file=output.png  OPSTEAM-2825
Fetching OPSTEAM-2825
Traceback (most recent call last):
  File "jira-dependency-graph.py", line 281, in <module>
    main()
  File "jira-dependency-graph.py", line 272, in main
    graph = graph + build_graph_data(issue, jira, options.excludes, options.show_directions, options.directions, options.includes, options.closed, options.ignore_epic, options.ignore_subtasks, options.traverse, options.word_wrap)
  File "jira-dependency-graph.py", line 199, in build_graph_data
    return walk(start_issue_key, [])
  File "jira-dependency-graph.py", line 149, in walk
    issue = jira.get_issue(issue_key)
  File "jira-dependency-graph.py", line 51, in get_issue
    response = self.get('/issue/%s' % key, params={'fields': self.fields})
  File "jira-dependency-graph.py", line 44, in get
    return requests.get(url, params=params, auth=self.auth, headers=headers, verify=(not self.no_verify_ssl))
  File "/home/carl/dev/.virtualenv/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/carl/dev/.virtualenv/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/carl/dev/.virtualenv/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/carl/dev/.virtualenv/lib/python2.7/site-packages/requests/sessions.py", line 616, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/carl/dev/.virtualenv/lib/python2.7/site-packages/requests/sessions.py", line 707, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'ira=https://[same FQDN]/rest/api/latest/issue/OPSTEAM-2825'

```

Any thoughts would be appreciated; I'm not a python dev but I do have some dev experience.

**Comment by pawelrychlik** [comment]
@CarlInglis just looking at the stacktrace - are you missing the double dash for `--jira=...` ?

**Comment by CarlInglis** [comment]
@pawelrychlik There really are days I shouldn't be allowed near a keyboard. Thanks! I now have a 404 - which is almost certainly me not being able to type - more coffee I think.
