### ISSUE TITLE
diacritics in link name causes app crash

### ISSUE THREAD

**Issue by bart9k** [pawelrychlik/jira-dependency-graph#34]
We have localized link names to Czech using diacritics. Then script process such link name it crashes with following: 

`Fetching RIO-1887`
`RIO-1887 => souvisí s => RIO-1897`
`Traceback (most recent call last):
  File "jira-dependency-graph.py", line 286, in <module>
    main()
  File "jira-dependency-graph.py", line 277, in main
    options.ignore_subtasks, options.traverse, options.word_wrap)
  File "jira-dependency-graph.py", line 201, in build_graph_data
    return walk(start_issue_key, [])
  File "jira-dependency-graph.py", line 197, in walk
    walk(child, graph)
  File "jira-dependency-graph.py", line 189, in walk
    result = process_link(fields, issue_key, other_link)
  File "jira-dependency-graph.py", line 142, in process_link
    link_type, extra)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 6: ordinal not in range(128)`

**Comment by bart9k** [comment]
This fixed my problem
`from __future__ import unicode_literals`

**Comment by pawelrychlik** [comment]
@bart9k if that's not too much to ask for - could you please send a pull-request? Thanks in advance.

**Comment by bart9k** [comment]
@pawelrychlik, I'll do bit more testing and if it is successful I'll pull my changes.

**Comment by bart9k** [comment]
Sorry for delay. But my suggested fix is not working well it covers issue only partially.
