### ISSUE TITLE
HttpError 401 when using JIRA Cloud

### ISSUE THREAD

**Issue by jfrantzius** [pawelrychlik/jira-dependency-graph#46]
Hi,
as already mentioned in #30 , when using jira-dependency-graph with JIRA cloud, unfortunately an HttpError 401 is received:
```
Traceback (most recent call last):
  File "/jira/jira-dependency-graph.py", line 302, in <module>
    main()
  File "/jira/jira-dependency-graph.py", line 291, in main
    graph = graph + build_graph_data(issue, jira, options.excludes, options.show_directions, options.directions,
  File "/jira/jira-dependency-graph.py", line 207, in build_graph_data
    return walk(start_issue_key, [])
  File "/jira/jira-dependency-graph.py", line 157, in walk
    issue = jira.get_issue(issue_key)
  File "/jira/jira-dependency-graph.py", line 49, in get_issue
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: [..]
```
That's really a pity, I was so looking forward to see that dependency graph :)

**Comment by mpavlikWandera** [comment]
@jfrantzius it works for me .... can you send full command that you use? of course with credentials redacted

**Comment by Regenhardt** [comment]
I didn't get a 401 (used --cookie=<JSESSIONID> for auth), but the rest api is different so the call for issues fails with 404.

**Comment by Regenhardt** [comment]
I updated my web version to use Jira Cloud, but only for api token auth for now, I broke cookie auth in the process: https://jiragraph.regenhardt.dev

**Comment by Andrwe** [comment]
@jfrantzius For me it worked with Jira Cloud by following these steps:

1. generate api token for my user via https://id.atlassian.com/manage-profile/security/api-tokens
2. run `jira-dependency-graph.py -u "jira-user-email-address" -p 'generated-api-token' --jira="https://prisma.atlassian.net"`
